rg_name             = "prod-rg"
location            = "East US"
vnet_name           = "prod-vnet"
vnet_address_space  = ["10.2.0.0/16"]
aks_name            = "prod-aks"
aks_dns_prefix      = "prodaks"
aks_agent_count     = 3
aks_vm_size         = "Standard_DS3_v2"
nsg_name            = "prod-nsg"
log_analytics_workspace_id = "your_workspace_id"  # Ensure this variable is defined in variables.tf
